fix(ripsecrets): don't exit on amending commits

diff --git a/.config/husky/pre-commit b/.config/husky/pre-commit
--- a/.config/husky/pre-commit
+++ b/.config/husky/pre-commit
@@ -3,8 +3,14 @@
 # shellcheck disable=SC1091
 . "$(dirname -- "$0")/_/husky.sh"
 
-command -v ripsecrets >/dev/null 2>&1 \
-	&& ripsecrets --strict-ignore \
+if command -v ripsecrets >/dev/null 2>&1; then
+	ripsecrets --strict-ignore \
 		"$(git diff --cached --name-only --diff-filter=ACM)" 2>/dev/null
+	status=$?
+	# Don't exit if amending w/ empty diff leads to exit code of 2.
+	if [ "$status" -ne 0 ] && [ "$status" -ne 2 ]; then
+		exit "$status"
+	fi
+fi
 
 pnpm run lint-staged
